name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo indir
      uses: actions/checkout@v4

    - name: Flutter kur
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Paketleri yükle
      run: flutter pub get

    - name: APK üret
      run: flutter build apk --release --target-platform android-arm64

    - name: APK yükle
      uses: actions/upload-artifact@v4
      with:
        name: babilpro
        path: build/app/outputs/flutter-apk/app-release.apk